// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVbOPEvqklSsDnMdhe9L8OVN0IcygSSKM',
    appId: '1:895421170259:web:d250cd7706c958d745fca6',
    messagingSenderId: '895421170259',
    projectId: 'fcmtest-fca31',
    authDomain: 'fcmtest-fca31.firebaseapp.com',
    storageBucket: 'fcmtest-fca31.firebasestorage.app',
    measurementId: 'G-9QNPB59GXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCECY7hYkIUO3-JTFJOS8TR7fhC1MGodOU',
    appId: '1:895421170259:android:80fdca6ae649731345fca6',
    messagingSenderId: '895421170259',
    projectId: 'fcmtest-fca31',
    storageBucket: 'fcmtest-fca31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgO2N81xlQGxFYJxJ14UQW8jYUlHtruR4',
    appId: '1:895421170259:ios:e8e75bb13c34d98b45fca6',
    messagingSenderId: '895421170259',
    projectId: 'fcmtest-fca31',
    storageBucket: 'fcmtest-fca31.firebasestorage.app',
    iosBundleId: 'com.example.fcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgO2N81xlQGxFYJxJ14UQW8jYUlHtruR4',
    appId: '1:895421170259:ios:e8e75bb13c34d98b45fca6',
    messagingSenderId: '895421170259',
    projectId: 'fcmtest-fca31',
    storageBucket: 'fcmtest-fca31.firebasestorage.app',
    iosBundleId: 'com.example.fcm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVbOPEvqklSsDnMdhe9L8OVN0IcygSSKM',
    appId: '1:895421170259:web:8908691c920544f945fca6',
    messagingSenderId: '895421170259',
    projectId: 'fcmtest-fca31',
    authDomain: 'fcmtest-fca31.firebaseapp.com',
    storageBucket: 'fcmtest-fca31.firebasestorage.app',
    measurementId: 'G-ZVGPXCLPH8',
  );
}
